### ISSUE TITLE
Add more example to do while loop 

### ISSUE THREAD

**Issue by Saurav-Sutaria** [Saurav-Sutaria/DS-Algo#1]

**Comment by Saurav-Sutaria** [comment]
Do while loop file modified  e1c4f584223ca0fb2fb56d9d8a8b1956e0ddb1de

**Comment by AnanyDubey** [comment]
Hey @Saurav-Sutaria, I would like to contribute to this project can you please describe the issue.

**Comment by Saurav-Sutaria** [comment]
Hey @AnanyDubey , you have to add some more examples in dowhile loop code file.
